### ISSUE TITLE
Filenames not psr-4 compatible 

### ISSUE THREAD

**Issue by akeiper** [smart2pay/SDK-PHP#2]
I have installed the SDK using composer however when running the code on a Linux server I am receiving an error saying:

```
Fatal error: Class 'S2P_SDK\S2P_SDK_Language' not found in /home/travis/build/zumba/service/lib/smart2pay/sdk-php/classes/s2p_sdk_module.php
````

I noticed while looking at the class directory that the class name is all lower case. The psr-4 standard states that the class names are case-sensitive. Here is a link to the standards: https://www.php-fig.org/psr/psr-4/

We wanted to use the SDK for our project but until this issue is resolved we can not use it due to the fatal errors since the filesystem on Linux boxes is case-sensitive.

**Comment by andys2p** [comment]
Hi akeiper,

You are right, it isn't psr-4 compatible atm. You should check samples directory to see how to initiate payments. You should only include bootstrap.php script.

Best regards,
Andy

**Comment by akeiper** [comment]
@andys2p currently we are including the package through composer. This is how we include all our dependencies.  In your composer.json it states the  SDK as psr-4 compatible. 

https://github.com/smart2pay/SDK-PHP/blob/master/composer.json#L32

**Comment by andys2p** [comment]
Hi akeiper,

I will schedule a new release which will be PSR-4 compatible. Will let you know.

Best regards,
Andy

**Comment by akeiper** [comment]
@andys2p that would be great! thank you!

**Comment by andys2p** [comment]
Hi @akeiper,

We just realeased Smart2Pay PHP SDK v2.1.1

https://github.com/smart2pay/SDK-PHP/releases/tag/v2.1.1

Please let us know if you have any problems integrating our SDK in your environment.

Best regards,
Andy

**Comment by akeiper** [comment]
@andys2p, just did a composer update and everything looks to be working nicely now. thank you for your quick response and help with this.

**Comment by andys2p** [comment]
Hi @akeiper,

Great! Let us know if you need further assistance.

Best regards,
Andy
